### ISSUE TITLE
Orc War Chief (MM)

### ISSUE THREAD

**Issue by agjwilson** [mlenser/roll20#34]
**Orc Wars Chiefs Attacks are importing wrong for me.** 

![error](https://cloud.githubusercontent.com/assets/18452351/23085786/8178bf2a-f561-11e6-8199-5bc3b0e5d66e.jpg)

**I think it should read:**

Greataxe. Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 14 (1d12 + 4 plus 1d8) slashing damage. 

Spear. Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 12 (1d6 + 4 plus 1d8) piercing damage, or 13 (2d8 + 4) piercing damage if used with two hands to make a melee attack.

**Comment by mlenser** [comment]
Please use https://bitbucket.org/mlenser/5eshaped/issues
